const state={lang:localStorage.getItem('bk_lang')||'en',active:'home'};
const L={
 en:{tagline:'Safe Foreign Jobs & Visa Guide',brandWord:'BAHARKAAM',heroTitle:'Safe Foreign Jobs & Visa Guide',heroSub:'For South Asian workers going to Gulf, Europe & worldwide.',safety:'Safety',sathiAI:'Sathi AI',sathiSub:'Ask anything about jobs, visa, salary, safety...',planSafe:'Plan Safe',avoidFraud:'Avoid Fraud',knowReality:'Know Reality',paySafe:'Pay Safe',roadmapTitle:'Safe Job Roadmap',roadmapDesc:'Job se travel tak safe steps',visaTitle:'Visa Fraud Check',visaDesc:'Pay karne se pehle visa, ticket aur offer check karein',salaryTitle:'Salary Guide',salaryDesc:'Country & role salary reality',moneyTitle:'Money & Govt Help',moneyDesc:'Payment, loan & official help',startGuide:'Start Guide',checkBeforePaying:'Check Before Paying',checkSalary:'Check Salary',getHelp:'Get Help',latestAlert:'Latest Safety Alert',alertText:'Beware of fake offer letters, fake ticket / PNR and advance payment scams. Do not pay without official verification.',reportSimilar:'Report Similar Scam',popularRoles:'Popular Job Roles',viewAllRoles:'View All Roles',featuredJobs:'Featured Safe Jobs',viewAllJobs:'View All Jobs',popularGuides:'Popular Safety Guides',viewAllGuides:'View All Guides',saveHistory:'Save Your Safety History',loginPrompt:'Mobile number se login karein, taaki aapki safety profile, saved guides aur job interest secure rahe.',login:'Login / Sign Up',guest:'Continue as Guest',navHome:'Home',navJobs:'Jobs',navSathi:'Sathi AI',navProfile:'Profile',navSOS:'SOS',jobsTitle:'Jobs / Naukri',jobsSub:'Source-check style job information. User must verify officially.',voiceTitle:'Bolkar Poochhein',voiceSub:'Sathi AI se job, visa, salary ya fraud related sawal poochein.',startVoice:'Start Voice Demo',demoProfile:'Demo Profile',dashboardTitle:'Abroad Safety Dashboard',dashboardSub:'Your profile stays private until you give consent.',checkPending:'Check Pending',profileCompletion:'Profile Completion',completeSteps:'Complete safety details before sharing interest.',abroadPlan:'My Abroad Plan',departureChecklist:'Safe Departure Checklist',myChecks:'My Safety Checks',savedGuides:'Saved Guides',familyHub:'Family Safety Hub',proofLocker:'Proof Locker',recruiterPermission:'Recruiter Sharing Permission',consentText:'Your profile will never be shared with recruiters/companies without your consent.',sosTitle:'SOS & Scam Help',sosSub:'Fraud, passport, salary, emergency ya videsh mein fasne ki situation mein safe steps follow karein.',sosNotice:'BaharKaam emergency service nahi hai. Hum safety guidance aur report collection platform hain.',reportScam:'Report Scam',submitReview:'Submit Report for Review',myProfile:'My Profile',recruiters:'For Recruiters / Companies',language:'Language',help:'Help',privacy:'Privacy',terms:'Terms'},
 hi:{tagline:'Safe Foreign Jobs & Visa Guide',heroTitle:'Safe Foreign Jobs & Visa Guide',heroSub:'Gulf, Europe aur worldwide jane wale South Asian workers ke liye.',sathiSub:'Job, visa, salary, safety ke bare mein kuch bhi poochhein...',loginPrompt:'Mobile number se login karein, taaki aapki safety profile, saved guides aur job interest secure rahe.',navJobs:'Jobs / Naukri',voiceTitle:'Bolkar Poochhein',dashboardTitle:'Abroad Safety Dashboard',sosTitle:'SOS & Scam Help'},
 ur:{tagline:'محفوظ بیرونی نوکریاں اور ویزا گائیڈ',heroTitle:'محفوظ بیرونی نوکریاں اور ویزا گائیڈ',heroSub:'گلف، یورپ اور دنیا بھر جانے والے جنوبی ایشیائی ورکروں کے لیے۔',sathiAI:'ساتھی AI',sathiSub:'نوکری، ویزا، تنخواہ اور سیفٹی کے بارے میں پوچھیں...',navHome:'ہوم',navJobs:'نوکریاں',navProfile:'پروفائل',navSOS:'SOS'},
 bn:{tagline:'নিরাপদ বিদেশি চাকরি ও ভিসা গাইড',heroTitle:'নিরাপদ বিদেশি চাকরি ও ভিসা গাইড',heroSub:'গালফ, ইউরোপ ও বিশ্বে যেতে চাওয়া দক্ষিণ এশিয়ার কর্মীদের জন্য।',sathiSub:'চাকরি, ভিসা, বেতন, সেফটি নিয়ে প্রশ্ন করুন...',navHome:'হোম',navJobs:'চাকরি',navProfile:'প্রোফাইল'},
 ne:{tagline:'सुरक्षित विदेशी काम र भिसा गाइड',heroTitle:'सुरक्षित विदेशी काम र भिसा गाइड',heroSub:'गल्फ, युरोप र विश्वभर जान चाहने दक्षिण एशियाली कामदारका लागि।',sathiSub:'काम, भिसा, तलब र सुरक्षा बारे सोध्नुहोस्...',navHome:'होम',navJobs:'काम',navProfile:'प्रोफाइल'}
};
const langNames={en:'English',hi:'Hindi',ur:'Urdu',bn:'Bengali',ne:'Nepali'};
const roles=['🚗 Driver','🏭 Factory & Packing','🏗️ Construction','👷 Helper / Labour','🧹 Cleaner','🛡️ Security','⚡ Electrician','🔥 Welder'];
const jobs=[{id:'dubai-driver',title:'Dubai Driver',country:'UAE',place:'Dubai',salary:'AED 1,800–2,200 / month',visa:'Work Visa Only',facilities:'Food + Room + Ticket',source:'Source Checked',risk:'Low Risk Indicators',docs:'Passport, Driving License, CV',warning:'User must verify offer letter and visa from official sources.',role:'Driver'},{id:'saudi-helper',title:'Construction Helper',country:'Saudi Arabia',place:'Riyadh',salary:'SAR 900–1,200 / month',visa:'Work Visa Only',facilities:'Food + Room + Ticket',source:'Needs Official Verification',risk:'Medium Risk',docs:'Passport, Medical, CV',warning:'Verify company details and visa stamp from official portal.',role:'Construction'},{id:'qatar-cleaner',title:'Cleaner / Housekeeping',country:'Qatar',place:'Doha',salary:'QAR 900–1,100 / month',visa:'Work Visa Only',facilities:'Food + Room',source:'Needs Official Verification',risk:'Medium Risk',docs:'Passport, Medical, CV',warning:'Check duty hours, contract copy and accommodation details before payment.',role:'Cleaner'}];
const guides=[['🛡️','Fake Visa Check','Official QR/portal se visa details verify karne ka guide.','visa-guide'],['🎫','Ticket / PNR Fraud','PNR, airline website aur fake ticket warning signs.','pnr-guide'],['🚗','Dubai Driver Salary','Real salary range, duty hours and facilities reality.','salary-guide'],['🇪🇺','Europe Work Guide','Poland, Croatia, Romania ke work route safety points.','europe-guide']];
const featureData={roadmap:{title:'Safe Job Roadmap',items:['Role aur country choose karein','Passport, CV, medical aur license checklist','Agent payment se pehle written receipt check','Offer letter, visa aur ticket verify karein','Travel se pehle family safety summary share karein'],actions:['Save Roadmap','Family Ko Bhejo']},visa:{title:'Visa Fraud Check',items:['Offer letter company name check','Visa number / QR official source par verify','Ticket / PNR airline website par check','Agent license, office and receipt check','Advance payment risk score placeholder'],actions:['Start Safety Check','Report Doubt']},salary:{title:'Salary Reality Guide',items:['Country aur role salary range dekhein','Food, room, ticket included hai ya nahi','Duty hours aur overtime terms check','Contract salary aur promised salary match karein','Low salary / high fee warning signs'],actions:['View Salary Reality','Save Guide']},money:{title:'Money & Official Help',items:['Agent payment receipt checklist','Loan safety and interest warning','No hawala / unregulated channel reminder','Family payment summary template','Official help contacts will be added after verification'],actions:['Open Money Safety Guide','Save Summary']}};
function t(k){return (L[state.lang]&&L[state.lang][k])||L.en[k]||k}
function applyLang(){document.documentElement.dir=state.lang==='ur'?'rtl':'ltr';document.getElementById('active-lang').textContent=langNames[state.lang];document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));renderAll()}
function setLanguage(lang){state.lang=lang;localStorage.setItem('bk_lang',lang);hideMenus();applyLang();toast(langNames[lang]+' selected')}
function toggleLangMenu(e){e.stopPropagation();document.getElementById('lang-menu').classList.toggle('hidden');document.getElementById('side-menu').classList.add('hidden')}
function toggleMenu(e){e.stopPropagation();document.getElementById('side-menu').classList.toggle('hidden');document.getElementById('lang-menu').classList.add('hidden')}
function hideMenus(){document.getElementById('lang-menu').classList.add('hidden');document.getElementById('side-menu').classList.add('hidden')}
document.addEventListener('click',hideMenus);
function switchScreen(id){state.active=id;document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active-screen'));document.getElementById('screen-'+id).classList.add('active-screen');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.tab===id));window.scrollTo({top:0,behavior:'smooth'});hideMenus()}
function renderRoles(){let html=roles.map(r=>`<button onclick="roleClick('${r.replace(/^\S+\s/,'')}')">${r}</button>`).join('');document.getElementById('home-role-chips').innerHTML=html}
function roleClick(role){switchScreen('jobs');document.getElementById('filter-role').value=role.includes('Factory')?'Factory':role.split(' ')[0];renderJobs();toast('Role filter: '+role)}
function jobCard(job,home=false){let med=job.risk.includes('Medium');return `<article class="job-card"><div class="job-top"><div><h4>${job.title}</h4><p>${job.country} · ${job.place}</p></div><span class="risk-pill ${med?'risk-medium':''}">${job.risk}</span></div><div class="job-meta"><div><span>Salary</span><b>${job.salary}</b></div><div><span>Visa Type</span><b>${job.visa}</b></div><div><span>Facilities</span><b>${job.facilities}</b></div><div><span>Documents</span><b>${job.docs}</b></div></div><div class="warning">⚠️ ${job.warning}</div><div class="job-actions"><button onclick="openJob('${job.id}')">View Safety Details</button><button class="outline" onclick="openLogin()">Interested Hoon</button><button class="outline" onclick="openSource('${job.id}')">Verify Source</button>${home?'':`<button class="outline" onclick="openModal('family')">Family Ko Bhejo</button>`}</div></article>`}
function renderJobs(){let c=document.getElementById('filter-country')?.value||'all',r=document.getElementById('filter-role')?.value||'all',risk=document.getElementById('filter-risk')?.value||'all';let list=jobs.filter(j=>(c==='all'||j.country===c)&&(r==='all'||j.role.includes(r)||j.title.includes(r))&&(risk==='all'||j.risk===risk));document.getElementById('jobs-list').innerHTML=(list.length?list:jobs).map(j=>jobCard(j,false)).join('')}
function renderHomeJobs(){document.getElementById('home-jobs').innerHTML=jobs.slice(0,2).map(j=>jobCard(j,true)).join('')}
function renderGuides(){document.getElementById('home-guides').innerHTML=guides.map(g=>`<button class="guide-card" onclick="openGuide('${g[3]}')"><span>${g[0]}</span><h4>${g[1]}</h4><p>${g[2]}</p></button>`).join('')}
function renderPrompts(){let prompts=['Dubai driver salary kitni hoti hai?','Visa fake hai ya nahi kaise check karun?','Agent advance payment maang raha hai kya karun?','Saudi mein salary nahi mili to kya karein?','Ticket / PNR kaise check karein?','Main videsh mein fas gaya hoon'];document.getElementById('quick-prompts').innerHTML=prompts.map(p=>`<button onclick="toast('Demo answer: ${p}')">${p}</button>`).join('')}
function renderSos(){let items=[['🚨','Emergency Now','Immediate safety steps'],['📝','Report Scam','Submit report for review'],['🏛️','Get Official Help','Verified contacts later'],['🛂','Passport & Exit Help','Passport held / exit help'],['💵','Salary & Labour Rights','Salary mismatch help'],['👨‍👩‍👧','Family Help','Share safety summary'],['📁','Proof Locker','Save proof placeholders'],['📢','Community Scam Alerts','Reviewed anonymous alerts'],['🌍','Country-wise Help','Country safety guide']];document.getElementById('sos-grid').innerHTML=items.map(i=>`<button onclick="${i[1]==='Report Scam'?'openReportScam()':'openModal(\'sosInfo\')'}"><span>${i[0]}</span><b>${i[1]}</b><small>${i[2]}</small></button>`).join('')}
function renderAll(){renderRoles();renderHomeJobs();renderJobs();renderGuides();renderPrompts();renderSos()}
function openFeature(key){let f=featureData[key];openModal('custom',`<h2>${f.title}</h2><p>BaharKaam guidance only. User must verify official documents before payment or travel.</p><ul class="modal-list">${f.items.map(x=>`<li>${x}</li>`).join('')}</ul><div class="modal-actions">${f.actions.map((a,i)=>`<button class="${i?'outline':''}" onclick="toast('${a} demo')">${a}</button>`).join('')}</div>`)}
function openJob(id){let j=jobs.find(x=>x.id===id);openModal('custom',`<h2>${j.title}</h2><p><b>${j.country} · ${j.place}</b></p><ul class="modal-list"><li>Salary: ${j.salary}</li><li>Visa Type: ${j.visa}</li><li>Facilities: ${j.facilities}</li><li>Source Status: ${j.source}</li><li>Risk Level: ${j.risk}</li><li>Documents: ${j.docs}</li><li>Warning: ${j.warning}</li></ul><div class="modal-actions"><button onclick="openLogin()">Interested Hoon</button><button class="outline" onclick="openSource('${id}')">Verify Source</button></div>`)}
function openSource(id){openModal('custom',`<h2>Verify Source</h2><p>Source Checked ka matlab guarantee nahi hai. User ko official source se verify karna zaroori hai.</p><ul class="modal-list"><li>Company / agency registration check</li><li>Offer letter company details match</li><li>Work visa official portal check</li><li>Receipt and payment proof save karein</li></ul>`)}
function openGuide(id){let g=guides.find(x=>x[3]===id);openModal('custom',`<h2>${g[1]}</h2><p>${g[2]}</p><ul class="modal-list"><li>Step-by-step original safety guide placeholder</li><li>Official verification reminder</li><li>Before payment checklist</li><li>Family ko summary bhejne ka option</li></ul><div class="modal-actions"><button onclick="toast('Guide saved demo')">Save Guide</button><button class="outline" onclick="openModal('allGuides')">View All Guides</button></div>`)}
function openReportScam(){document.getElementById('report-form')?.classList.remove('hidden');document.getElementById('report-form')?.scrollIntoView({behavior:'smooth',block:'start'})}
function openLogin(){openModal('custom',`<h2>${t('login')}</h2><p>${t('loginPrompt')}</p><div class="modal-list"><li>Mobile OTP login later</li><li>Saved guides and checks</li><li>Job interest history</li><li>Consent-based profile sharing</li></div><div class="modal-actions"><button onclick="toast('Login demo')">Login / Sign Up</button><button class="outline" onclick="closeModal()">Continue as Guest</button></div>`)}
function openModal(type,custom){let body=custom;if(!body){const map={saved:['Saved Guides','Your saved guide placeholders will appear here.'],language:['Language','Choose English, Hindi/Hinglish, Urdu, Bengali or Nepali from the top language menu.'],help:['Help','Ask Sathi AI or open SOS for fraud/passport/salary emergency guidance.'],privacy:['Privacy','Your phone number and profile details will not be shared with recruiters/companies without your consent.'],terms:['Terms','BaharKaam provides guidance only. We do not guarantee jobs or visas.'],about:['About BaharKaam','Safety-first foreign work guidance platform for South Asian workers.'],contact:['Contact','Contact form will be added later after source verification.'],disclaimer:['Disclaimer','BaharKaam is not a visa agency, recruitment agency or government website. Always verify details from official sources.'],plan:['My Abroad Plan','Demo abroad plan: Saudi Arabia · Carpenter · Work visa check pending.'],checks:['My Safety Checks','Visa, ticket, offer letter and agent check history placeholders.'],family:['Family Safety Hub','Share job summary, agent details and travel plan with family.'],proof:['Proof Locker','Photos, screenshots, receipts and document proof placeholders.'],sosInfo:['Official Help','Official contact details will be added after source verification. Always confirm from embassy/government website before calling.'],allGuides:['All Safety Guides','Fake Visa Check, Ticket / PNR Fraud, Dubai Driver Salary, Qatar Cleaner Salary, Europe Work Guide, Agent Payment Safety Guide.'],recruiter:['For Recruiters / Companies','BaharKaam reviews hiring requirements before showing them to workers. Fake, unclear, misleading or guaranteed job/visa posts are not allowed. Worker profiles will never be shared without their consent.']};let m=map[type]||['BaharKaam','Demo modal'];body=`<h2>${m[0]}</h2><p>${m[1]}</p>`;if(type==='recruiter')body+=`<div class="modal-list"><li>Agency / Company Name</li><li>License / Registration Number</li><li>Job Country, Role, Workers Needed</li><li>Salary, Visa Type, Food / Room / Ticket</li><li>Service Charge / Fees</li></div><div class="modal-actions"><button onclick="toast('Recruiter form demo')">Submit Requirement</button></div>`}document.getElementById('modal-content').innerHTML=body;document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
function toast(msg){let el=document.getElementById('toast');el.textContent=msg;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),1900)}
applyLang();
